baseURL = "https://www.anthonyoconnor.ca/"
languageCode = "en-us"
title = "Anthony O'Connor"
theme = "hugo-aoc"

[params]
  author = "Anthony O'Connor"
  description = "Anthony O'Connor"

preserveTaxonomyNames = true

[[menu.main]]
    name = "About"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Résumé"
    url = "/Resume"
    weight = 2

[[menu.main]]
    name = "Blog"
    url = "/blog"
    weight = 3